apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "demo-app.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: "2"
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "demo-app.fullname" . }}
            port:
              number: 80
  ingressClassName: nginx
